### ISSUE TITLE
Spline is not creating.

### ISSUE THREAD

**Issue by saquibansari0101** [methusalah/SplineMesh#56]
Whenever I go to GameObject>3D Object>Spline no Spline object is created and when i imported the package it used to create Spline but in sometime it becomes non editable. I re-imported but it doesn't work.

**Comment by benoit-dumas** [comment]
Can't reproduce on 2021.4.14. Any error message?

Le ven. 25 mars 2022 à 17:55, Saquib Akhtar ***@***.***> a
écrit :

**Comment by saquibansari0101** [comment]
> Unity 2020.3.25f

I am using Spline by first creating an empty game object and then adding Spline component.

Actually in demo scene of splinemesh all things works fine. But in my scenes it doesn't works. Like if I add Spline Mesh Tiling component it doesn't tile it.

No error nothing shows in console

**Comment by benoit-dumas** [comment]
Sorry your test case is not specific enough for me to understand what the matter is.

You create an empty game object, then add the Spline component and the SplineMeshTiling component on it.

The gyzmo of a two-nodes arched spline should appear when you select the object.

Now to tile a mesh along the spline, you need to add that mesh to the SplineMeshTiling and set a transformation to apply to the mesh before it is tiled. You also need to specify the tiling mode etc.

What exactly goes wrong in this process?

**Comment by saquibansari0101** [comment]
![image](https://user-images.githubusercontent.com/45628219/160173361-3019e9ca-94bd-464f-8d52-697841a33f79.png)

I am trying to create basic pipe and use its meshcollider for navmesh. but in prefab the pipe is not visible and in demo scene the pipe is visible so I thought its not creating.

I copy pasted a sample component to my prefab but the pipe is not visible, only its gizmo is visible.

**Comment by benoit-dumas** [comment]
Indeed the content is not generated in the prefab editor. Since 2018.4, a
prefab instance hierarchy cannot be changed in the scene, but SplineMesh
needs to update the generated game object in many situations, hence need to
be able to remove the previous ones. Content is only generated in the scene
where the prefabs are instantiated, but of course you can change the code
if you wish ^^

Le ven. 25 mars 2022 à 18:44, Saquib Akhtar ***@***.***> a
écrit :

**Comment by saquibansari0101** [comment]
Yes, Thanks for assistance.
